### ISSUE TITLE
Installation issue - Obsidian (v1.6.7) - MacOS (v14.6.1)

### ISSUE THREAD

**Issue by buttonpushertv** [Ordeeper/obsidian-journaling-plugin#1]
Following the README instructions, I downloaded the plugin as a zip file from the GitHub page using the green "Code" button. This downloads a file called: `obsidian-journaling-plugin-main.zip` I also tried downloading the `Source Code` .zip file directly from the Releases page (v1.0.0) - which dowloads a file called `obsidian-journaling-plugin-1.0.0.zip`.

Unzipping either of those files into any of the following folders does not seem to enable the plugin for use:
- (my vault's .obsidian folder)/plugins/obisidian-journaling-plugin-main
- (my vault's .obsidian folder)/plugins/obisidian-journaling-plugin
- (my vault's .obsidian folder)/plugins/journaling

Any of the above *will* show the plugin in the Community Plugins list but produces an error: 
`Failed to load plugin "journaling"` (or `Failed to load plugin "obsidian-journaling-plugin"`) when you try to enable it.

After each different path name, I did restart Obsidian.

FWIW, the code downloaded from the main page, shows `"id": "journaling"` on the top of the `manifest.json` file, whereas the same line from the Release source code .zip file shows `"id": "obsidian-journaling-plugin"` in its `manifest.json`. So, I'm not sure which path should be used to allow the plugin to be enabled.

What should the folder for the plugin be named?

One (maybe important) point is that I'm running in to these issues on Obsidian (v.1.6.7) running on MacOS (Sonoma 14.6.1). Don't know if that matters.

**Comment by Ordeeper** [comment]
Can you try downloading from community plugins?

![image](https://github.com/user-attachments/assets/7dc864e1-2553-4cd9-9bba-a22d031b2480)

**Comment by buttonpushertv** [comment]
I didn't see it on my first search there, but it showed up for me now.

I have it working now. Thanks.

**Comment by buttonpushertv** [comment]
All good now. Thanks.

You may want to update the README with install instructions via Community Plugins browser.

**Comment by Ordeeper** [comment]
Thanks, I will do that
